### ISSUE TITLE
关于论文中图4和图10的一些疑问。

### ISSUE THREAD

**Issue by sev777** [kunkun0w0/SGA#1]
你好，请问一下该论文中的图4和图10是如何绘制的呢？ 在计算cos(g,g_*)时，梯度g的维度是多少？如果是高维是如何使用代码实现的呢？ 谢谢！

**Comment by kunkun0w0** [comment]
Sorry for the latter reply. I am busy in PhD application.

> Q: 请问一下该论文中的图4和图10是如何绘制的呢？

A: I use tensorboard to draw offset histograms (Fig. 4 and Fig. 10)

https://github.com/kunkun0w0/SGA/blob/01f5999839364cb00dbe6f7b7c195ce663225caf/SCFT_with_gradient_cosine_logging/solver.py#L400-L403

> Q: 在计算cos(g,g_*)时，梯度g的维度是多少？

A: The dimension equal to the feature dimension.

> Q: 如果是高维是如何使用代码实现的呢？

A: You can according to the following code.

https://github.com/kunkun0w0/SGA/blob/01f5999839364cb00dbe6f7b7c195ce663225caf/SCFT_with_gradient_cosine_logging/solver.py#L189-L195
